# ============================================================================
# Title       : Standalone Nuclide ID Engine (f64 Fully Accessible Zero-Copy)
# Architecture: x86_64 | Linux SysV ABI | AT&T Syntax
# Description : Headless GPU Execution with Read/Write protected memory maps
#               and synchronous sys_exit_group thread termination.
# Author      : agguro
# ============================================================================

.section .rodata
    .align 16
    db_file:     .string "isotopes.bin"
    data_file:   .string "decay_data.bin"
    func_name:   .string "learnDecayK"
    
    fmt_start:   .ascii "\033[1;34m[nuclideid]\033[0m Starting standalone hardware inference (f64)...\n"
    fmt_start_l: .long . - fmt_start
    fmt_match:   .ascii "\033[1;32m[IDENTIFICATIE GESLAAGD]\033[0m\n"
    fmt_match_l: .long . - fmt_match
    fmt_z:       .ascii "  Protonen (Z): "
    fmt_z_l:     .long . - fmt_z
    fmt_a:       .ascii "  Massa (A):    "
    fmt_a_l:     .long . - fmt_a
    fmt_name:    .ascii "  Nuclide:      "
    fmt_name_l:  .long . - fmt_name
    fmt_nl:      .ascii "\n"

    fmt_nocuda:   .ascii "\033[1;31m[ERROR]\033[0m No NVIDIA GPU or driver detected on this system.\n"
    fmt_nocuda_l: .long . - fmt_nocuda

    fmt_nomod:    .ascii "\033[1;31m[ERROR]\033[0m Loaded CUDA data is corrupt or rejected by driver.\n"
    fmt_nomod_l:  .long . - fmt_nomod

    .align 8
cubin_start:
    .incbin "learn_decay.cubin"
cubin_end:

.section .data
    .align 16
    cu_ctx:       .quad 0
    cu_device:    .long 0
    cu_module:    .quad 0
    cu_function:  .quad 0
    
    d_data_ptr:   .quad 0          # Unified VRAM buffer for interleaved double2 array
    d_k_out:      .quad 0

    .align 8
    kernel_params:
        p_t:      .quad 0          # Maps to double2 array start (t axis)
        p_y:      .quad 0          # Maps to same start (kernel handles +8 stride internally)
        p_k:      .quad 0          # Destination for learned k parameter
        p_num:    .long 50         # Total samples generated by create_decay_data
    
    .align 8
    kernel_args:  .quad kernel_params, kernel_params+8, kernel_params+16, kernel_params+24

    fd_db:        .quad 0
    fd_data:      .quad 0
    ptr_db:       .quad 0
    ptr_data:     .quad 0
    
    .align 8
    stat_buf:     .zero 144

    .align 8
    learned_k:    .double 0.0      # Holds final 64-bit precision result from GPU
    k_float:      .float 0.0       # Downsampled 32-bit float for the database index matching

    .align 16
    ascii_buf:    .zero 32

.section .text
.globl _start
_start:
    # Force strict x86_64 SysV ABI 16-byte stack alignment
    pushq   %rbp
    movq    %rsp, %rbp
    andq    $-16, %rsp

    # ==========================================
    # CUDA INITIALIZATION
    # ==========================================
    xorl    %edi, %edi
    call    cuInit@PLT
    testl   %eax, %eax
    jnz     .L_cuda_error

    # Notify launch state via sys_write
    movl    $1, %eax
    movl    $1, %edi
    leaq    fmt_start(%rip), %rsi
    movl    fmt_start_l(%rip), %edx
    syscall

    # ==========================================
    # 1. FULLY ACCESSIBLE ZERO-COPY MEMORY MAPS
    # ==========================================
    
    # --- A. Map isotopes.bin (O_RDWR + PROT_READ|PROT_WRITE) ---
    movl    $2, %eax              # sys_open
    leaq    db_file(%rip), %rdi
    movl    $2, %esi              # O_RDWR (Required to unlock PROT_WRITE mapping)
    syscall
    movq    %rax, fd_db(%rip)

    movl    $9, %eax              # sys_mmap
    xorq    %rdi, %rdi
    movq    $131072, %rsi         # 128 KB page boundary allocation
    movl    $3, %edx              # PROT_READ | PROT_WRITE (Full hardware clearance)
    movl    $2, %r10d             # MAP_PRIVATE (Copy-On-Write protects raw binary file)
    movq    fd_db(%rip), %r8
    xorq    %r9, %r9
    syscall
    movq    %rax, ptr_db(%rip)

    # --- B. Map decay_data.bin (O_RDWR + PROT_READ|PROT_WRITE) ---
    movl    $2, %eax              # sys_open
    leaq    data_file(%rip), %rdi
    movl    $2, %esi              # O_RDWR
    syscall
    movq    %rax, fd_data(%rip)

    movl    $9, %eax              # sys_mmap
    xorq    %rdi, %rdi
    movq    $4096, %rsi           # 4 KB single memory page
    movl    $3, %edx              # PROT_READ | PROT_WRITE
    movl    $2, %r10d             # MAP_PRIVATE
    movq    fd_data(%rip), %r8
    xorq    %r9, %r9
    syscall
    movq    %rax, ptr_data(%rip)

    # ==========================================
    # 2. CUDA DRIVER SYSTEM CONTEXT ENGINE
    # ==========================================
    leaq    cu_device(%rip), %rdi
    xorl    %esi, %esi
    call    cuDeviceGet@PLT
    
    leaq    cu_ctx(%rip), %rdi
    xorl    %esi, %esi
    movl    cu_device(%rip), %edx
    call    cuCtxCreate_v2@PLT

    # Allocate physical VRAM space via Driver v2 endpoints
    leaq    d_data_ptr(%rip), %rdi
    movl    $1024, %esi           # Space for interleaved f64 double2 tuples
    call    cuMemAlloc_v2@PLT
    
    leaq    d_k_out(%rip), %rdi
    movl    $8, %esi              # 8 bytes for pure f64 learned parameter destination
    call    cuMemAlloc_v2@PLT

    # Stream the unified file memory map directly to VRAM
    movq    d_data_ptr(%rip), %rdi
    movq    ptr_data(%rip), %rsi   
    movl    $1024, %edx
    call    cuMemcpyHtoD_v2@PLT

    # Load compiled binary object from RAM
    leaq    cu_module(%rip), %rdi       
    leaq    cubin_start(%rip), %rsi     
    call    cuModuleLoadData@PLT
    testl   %eax, %eax
    jnz     .L_mod_error
    
    leaq    cu_function(%rip), %rdi
    movq    cu_module(%rip), %rsi
    leaq    func_name(%rip), %rdx
    call    cuModuleGetFunction@PLT

    # Bind active VRAM memory addresses into parameter structure map
    movq    d_data_ptr(%rip), %rax
    movq    %rax, kernel_params(%rip)       
    movq    %rax, (kernel_params+8)(%rip)   
    movq    d_k_out(%rip), %rax
    movq    %rax, (kernel_params+16)(%rip)

    # Launch execution grid (Grid: 1 block, Threads per block: 256)
    movq    cu_function(%rip), %rdi
    movl    $1, %esi              
    movl    $1, %edx
    movl    $1, %ecx
    movl    $256, %r8d            
    movl    $1, %r9d
    
    # Establish stable, flat ABI compliant stack frame for trailing arguments
    subq    $48, %rsp
    movq    $1, 0(%rsp)            # blockDimZ
    movq    $0, 8(%rsp)            # sharedMemBytes
    movq    $0, 16(%rsp)           # hStream
    leaq    kernel_args(%rip), %rax
    movq    %rax, 24(%rsp)         # kernelParams pointer
    movq    $0, 32(%rsp)           # extra options
    call    cuLaunchKernel@PLT
    addq    $48, %rsp

    call    cuCtxSynchronize@PLT

    # Retrieve learned high-fidelity f64 double from GPU core back to host RAM
    leaq    learned_k(%rip), %rdi
    movq    d_k_out(%rip), %rsi
    movl    $8, %edx
    call    cuMemcpyDtoH_v2@PLT

    # ==========================================
    # 3. HIGH PERFORMANCE CPU BINARY SEARCH
    # ==========================================
    # Convert final f64 double back to f32 float to align with database architecture
    movsd   learned_k(%rip), %xmm0
    cvtsd2ss %xmm0, %xmm0                 
    movss   %xmm0, k_float(%rip)

    movq    ptr_db(%rip), %r12     
    xorl    %ebx, %ebx                    # Low index bound = 0
    movl    $3387, %ecx                   # High index bound = 3388 records - 1

BINARY_SEARCH_LOOP:
    cmpl    %ecx, %ebx
    jg      FOUND_NEAREST               

    movl    %ebx, %eax
    addl    %ecx, %eax
    shrl    $1, %eax                      # Midpoint division

    movl    %eax, %edx
    shll    $5, %edx                      # Mid * 32 bytes structure stride mapping
    addq    %r12, %rdx                    # %rdx = Absolute midpoint record address

    movss   (%rdx), %xmm1                 # Pull database k constant value from offset 0

    comiss  %xmm1, %xmm0
    je      MATCH_EXACT                 
    ja      SEARCH_HIGHER               

    movl    %eax, %ecx
    decl    %ecx                          # High bound shift = Mid - 1
    jmp     BINARY_SEARCH_LOOP

SEARCH_HIGHER:
    movl    %eax, %ebx
    incl    %ebx                          # Low bound shift = Mid + 1
    jmp     BINARY_SEARCH_LOOP

MATCH_EXACT:
    jmp     PRINT_DETERMINATION

FOUND_NEAREST:
    shll    $5, %ebx
    addq    %r12, %rbx
    movq    %rbx, %rdx                    # Default fallback to closest match boundary

    # ==========================================
    # 4. BARE-METAL OUTPUT GENERATOR
    # ==========================================
PRINT_DETERMINATION:
    movq    %rdx, %r15                     

    movl    $1, %eax
    movl    $1, %edi
    leaq    fmt_match(%rip), %rsi
    movl    fmt_match_l(%rip), %edx
    syscall

    movl    $1, %eax
    movl    $1, %edi
    leaq    fmt_z(%rip), %rsi
    movl    fmt_z_l(%rip), %edx
    syscall

    movl    8(%r15), %eax                 # Proton number Z located at record offset 8
    call    print_uint

    movl    $1, %eax
    movl    $1, %edi
    leaq    fmt_a(%rip), %rsi
    movl    fmt_a_l(%rip), %edx
    syscall

    movl    4(%r15), %eax                 # Mass number A located at record offset 4
    call    print_uint

    movl    $1, %eax
    movl    $1, %edi
    leaq    fmt_name(%rip), %rsi
    movl    fmt_name_l(%rip), %edx
    syscall

    leaq    12(%r15), %rsi                # Element text string begins at record offset 12
    xorl    %edx, %edx
LEN_LOOP:
    cmpb    $0, (%rsi,%rdx)
    je      PRINT_NAME
    incq    %rdx
    jmp     LEN_LOOP
PRINT_NAME:
    movl    $1, %eax
    movl    $1, %edi
    syscall

    movl    $1, %eax
    movl    $1, %edi
    leaq    fmt_nl(%rip), %rsi
    movl    $1, %edx
    syscall

    # Clean teardown, stack reset and whole-group execution termination
    movq    %rbp, %rsp
    popq    %rbp
    movl    $231, %eax                    # sys_exit_group (Nuke all child/driver threads)
    xorl    %edi, %edi                    # Exit code 0
    syscall

# --- STACK-PROOF INT TO ASCII SERIALIZER ---
print_uint:
    leaq    (ascii_buf + 31)(%rip), %rcx       
    movb    $10, (%rcx)          
    movq    $10, %r8                      
.L_conv:
    xorl    %edx, %edx
    divq    %r8
    addb    $48, %dl                      
    decq    %rcx
    movb    %dl, (%rcx)
    testq   %rax, %rax
    jnz     .L_conv
    
    leaq    (ascii_buf + 32)(%rip), %rdx
    subq    %rcx, %rdx
    movl    $1, %eax
    movl    $1, %edi
    movq    %rcx, %rsi
    syscall
    ret

.L_cuda_error:
    movl    $1, %eax              
    movl    $2, %edi              
    leaq    fmt_nocuda(%rip), %rsi
    movl    fmt_nocuda_l(%rip), %edx
    syscall
    movq    %rbp, %rsp
    popq    %rbp
    movl    $231, %eax                    # sys_exit_group
    movl    $1, %edi                      # Exit code 1
    syscall

.L_mod_error:
    movl    $1, %eax              
    movl    $2, %edi              
    leaq    fmt_nomod(%rip), %rsi
    movl    fmt_nomod_l(%rip), %edx
    syscall
    movq    %rbp, %rsp
    popq    %rbp
    movl    $231, %eax                    # sys_exit_group
    movl    $1, %edi                      # Exit code 1
    syscall

.size _start, . - _start
.section .note.GNU-stack,"",@progbits
